### ISSUE TITLE
Firefox: Header hides text

### ISSUE THREAD

**Issue by observant2** [mailjet/api-documentation#10]
On Firefox 58.0:

![grafik](https://user-images.githubusercontent.com/18561536/35848165-5c7705ec-0b1d-11e8-818a-cd2b06c96f58.png)

(Already scrolled to the top.)

**Comment by adamyanliev** [comment]
Hi,
This was fixed with an update after the redesign of the header. Thanks for letting us know - I'm closing the issue now.
