### ISSUE TITLE
SMTP `X-MJ-TemplateLanguage` description does not fit reality

### ISSUE THREAD

**Issue by note** [mailjet/api-documentation#11]
I am not sure if this is the best place to report that issue (there are quite a lot of repos in `mailjet`) so putting it here.

https://dev.mailjet.com/template-language/SMTP/ states that:

```
X-MJ-TemplateLanguage - set to true to have the templating language interpreted
```

Apparently the documentation is wrong - after a few hours of painful guessing I finally discovered that setting it to "1" (instead of "true" or "True") actually works.

**Comment by adamyanliev** [comment]
Hello,

Thanks for letting us know - it will be updated shortly with the new guide version. And apologies for the delayed response.

**Comment by DalfDev** [comment]
Still true in 2020.
