### ISSUE TITLE
Looks like payload limit is wrong in documentation

### ISSUE THREAD

**Issue by smiileTeam** [mailjet/api-documentation#12]
On api v3.1

> Limitation size of JSON payload
> The number of message objects authorised in the payload is now 100, also limiting the number of recipients ("To") authorised on one single Send API call.

With more than 50 recipients in payload (let's say 77 messages with only one recipient in each message in Messages array), we receive a error:

```
"result": {
    "ErrorIdentifier": "xxxx",
    "ErrorCode": "send-0015",
    "StatusCode": 400,
    "ErrorMessage": "Total number of recipients exceeded. Max allowed - 50.",
    "ErrorRelatedTo": [
        "To",
        "Bcc",
        "Cc"
    ]
}
```

please clarify

**Comment by adamyanliev** [comment]
Hello,

Apologies for the delayed response. The limit is 100 for users on Send API v3. For Send API v3.1 the limit is 50. Basically with v3 users can send higher volumes, while v3.1 is focused on faster deliverability - that is the reason behind the limit difference. 

We'll clarify the information in the next version of the guide, thanks for pointing this out.
