### ISSUE TITLE
Configuration for Contactlist Subscribe Event / Callback

### ISSUE THREAD

**Issue by franz-josef-kaiser** [mailjet/api-documentation#17]
We are trying to find a way to get subscription events (contacts to a contactlist) from MailJet to another parties system. When we looked at [the list of integrations](https://www.mailjet.com/integrations/#all), we saw, that there are quite some services which are able to subscribe to such an event (SalesForce, Zapier, etc.). How can we achieve this (via the UI or the API) and receive a payload in our webservices?

<img width="970" alt="subscribe-contactlist-mailjet-zapier-webhook" src="https://user-images.githubusercontent.com/387666/45036743-956a0300-b05d-11e8-9e96-aed846efa876.png">

**EDIT:** In the Subscription–Widget edit page, we found that we can edit the HTML for the confirmation page. There we can insert a script tag, which seems to get executed while writing. This way we could load external scripts and maybe send a request. Note, that this would be the worst scenario as we would need to manage all this manually for every different page and would end up in maintenance hell.

<img width="1242" alt="mailjet_contactform expert-mode" src="https://user-images.githubusercontent.com/387666/45037831-29d56500-b060-11e8-8bd1-c19386b4081c.png">

**Comment by kmanchikov** [comment]
Nice to be working with you on this one as well Franz. 

You could get subscribe-events from Zapier let's say, but currently this won't be possible through our Event API (https://dev.mailjet.com/guides/?php#event-api-real-time-notifications) which would have been your best solution without using third-parties etc. our Event API would push Real-time Events to a Webhook of yours as you can also see examples and set up steps from the article above.

Unfortunately we do not currently have (new-subscription) events through the Event API, and you would have to go through a third-party. 

Let me know if you do have any other questions or concerns on this or any other topic Franz, I would be happy to look into those. 

Best, 
Krasimir

**Comment by franz-josef-kaiser** [comment]
> Nice to be working with you on this one as well Franz.

Same here!

> (…) subscribe-events from Zapier (…) won't be possible through our Event API (…)

Just to clarify this one for me: Does _Zapier_… 

- use a _different_ API, provided only for partners of yours?
- or let they simple run a cronjob? (Assumption based on their "snyc interval"–documentation [link here](https://zapier.com/help/plans-pricing/#syncing-interval).)

If it's the later and you can confirm this, then we will set up a cron task ourself and poll your endpoints for updates.

**Comment by franz-josef-kaiser** [comment]
@kmanchikov ping :)

**Comment by kmanchikov** [comment]
Apologize for answering just now on this one. 

Zapier, doesn't use a different API especially build for them that I can tell. So I would more bet on the cronjob scenario judging by the article in their doc.

**Comment by franz-josef-kaiser** [comment]
Hi @kmanchikov ,
is setting up a webhook planned somehow? It's still incredibly annoying and disappointing to not have this in the basic set of webhooks. Thanks!

**Comment by martinblaha** [comment]
Hi,
is there any update on this? I'm trying to implement the exact same scenario and need to configure a webhook call on a new subscription signup (after it has been confirmed by double-opt-in).
Thanks.
Martin

**Comment by franz-josef-kaiser** [comment]
Ping @kmanchikov

**Comment by MalteHorstmann** [comment]
+1

**Comment by franz-josef-kaiser** [comment]
Ping @kmanchikov

**Comment by dnapainter** [comment]
+1 (the only service I've found so far offering this is Mailchimp ($$$$$)

**Comment by franz-josef-kaiser** [comment]
Seems like the original dev [left the building](https://github.com/orgs/mailjet/people).

pinging @Antoine87 @bench @ngarnier @Nightbr @Nikola-Andreev and @Tommy-42 to see who is ready to answer the question here ☝️ .

**Comment by ngarnier** [comment]
Hey @franz-josef-kaiser, we don't have any update regarding this feature request at this time. 

I'm going to close this issue as it is not related to documentation but rather a feature request. You can however file it on https://feedback.mailjet.com/ so that it is listed and others can upvote it too. Your feedback matters to us and we prioritize feature requests that benefit to the most.

**Comment by StefanEndress** [comment]
Please vote here → https://feedback.mailjet.com/forums/931474-feature-requests/suggestions/41000194-add-subscribe-event
