### ISSUE TITLE
How to get URl for single contact?

### ISSUE THREAD

**Issue by franz-josef-kaiser** [mailjet/api-documentation#19]
**Reason:** To switch between different systems which collect, enrich and display user data, we normally use buttons and links in the user interface to quickly "jump" from one system to the other. 
**Question:** Is it possible to retrieve the URl for a single contact via the API to inter-connect _MailJet_ for our end users? 
Thanks in advance!

**Comment by adamyanliev** [comment]
Hi @franz-josef-kaiser ,

Sorry, it's not quite clear to me what you need. 

Generally you can retrieve information about a contact via the API by doing a GET request on `https://api.mailjet.com/v3/REST/contact/{{contact_ID}}`. Alternatively, you can use the contact's email address instead of the `{{contact_ID}}`. Of course, authentication via API keys is needed.

Please give me an example of what you want to achieve, so I can understand your request better.

Regards,
Atanas

**Comment by franz-josef-kaiser** [comment]
Hi @adamyanliev ,
sorry, this issue must have slipped under my radar.
What I need from the response is a link to the user in MailJets User-Interface.

*Example:*
```
# Request 
$ curl -sX https://api.mailjet.com/v3/REST/contact/{{contact_ID}}

# Response
{
    …
    # plus a link to the user in the mj-user-interface: "2LNCsA"
}

# Final link: https://app.mailjet.com/contacts/overview/2LNCsA
```

I would need to retrieve or calculate/ hash/ whatever this link, so people at our point of sales can easily switch between different systems and read up the data they need, _without searching a contact_, but by simply _following a link to the contact_. This is need between for e.g. our ticket system and mj or our crm and mj.
Best,
Franz Josef

**Comment by adamyanliev** [comment]
Hi @franz-josef-kaiser,

We discussed this with the team and it was decided to move away from the hashed URIs - instead the URI will equal the contact ID. I'm reopening this issue and will leave a comment here, once the change is implemented.

FYI - the same will be done for contact lists as well.

Regards,
Atanas

**Comment by franz-josef-kaiser** [comment]
That's good news! Yes, please keep me updated!

**Comment by caercam** [comment]
Hi there! Any update on this change?

**Comment by ngarnier** [comment]
@CaerCam the change has been done, contact IDs are not hashed anymore in the URL: `https://app.mailjet.com/contacts/overview/{{contactID}}`.

**Comment by caercam** [comment]
Thanks @ngarnier. I thought this wasn't implemented yet as I'm only getting blank pages for valid contact ids.

**Comment by ngarnier** [comment]
Are you sure you're logged into the proper account or subaccount when following the link?

**Comment by caercam** [comment]
Think so. There's only one account (premium account) and I'm logged in correctly. I can see the overview page for the contact corresponding to the account's email, for instance, I can get that contact ID from the API, but replacing the hash with the contact ID in the URL gives me a blank page. Here are the response headers, if that helps:

```
HTTP/2 200 OK
date: Tue, 13 Oct 2020 17:54:28 GMT
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
set-cookie: mail_session=0a24c0117b5b41c781e998e197d8fbe4; expires=Tue, 13-Oct-2020 18:54:28 GMT; Max-Age=3600; path=/; domain=.mailjet.com; secure; HttpOnly; HttpOnly; Secure; SameSite=None
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
x-content-type-options: nosniff
content-encoding: gzip
strict-transport-security: max-age=31536000
X-Firefox-Spdy: h2
```

**Comment by ngarnier** [comment]
That's really strange, please open a support ticket from your account with all details possible, for example the API call you're making to retrieve the Contact ID and the URL you're trying to load.
