### ISSUE TITLE
Python API: actionid parameter should be action_id

### ISSUE THREAD

**Issue by msater** [mailjet/api-documentation#2]
There is bug in the code samples for Python:
from mailjet import Client
import os
api_key = os.environ['MJ_APIKEY_PUBLIC']
api_secret = os.environ['MJ_APIKEY_PRIVATE']
mailjet = Client(auth=(api_key, api_secret))
result = mailjet.contact_managemanycontacts.get(actionid='$JOBID')

should be
result = mailjet.contact_managemanycontacts.get(action_id='$JOBID')

There is also a bug in the python api to make it work, where can the issue be reported?

**Comment by WeshGuillaume** [comment]
Sorry for the delay, It will be fixed for the next release! Thanks

You can open an issue in the python github repo

Best,
Guillaume

**Comment by adamyanliev** [comment]
closing this as it was fixed a while ago.
