### ISSUE TITLE
ErrorCode:"mj-0004" Type mismatch

### ISSUE THREAD

**Issue by jahangir1rashdi** [mailjet/api-documentation#21]
Error message "ErrorRelatedTo":["Messages"],"ErrorMessage":"Type mismatch. Expected type \"Messages\".","StatusCode":400},{"ErrorIdentifier":"1b4b1134-3e65-4953-a1de-1e8dff883b7c","ErrorCode":"mj-0003","ErrorRelatedTo":["Messages"],"ErrorMessage":"Missing mandatory property.","StatusCode":400}],"Messages":[]}

my message code is 
     request = new MailjetRequest(Emailv31.resource)
                .property(Emailv31.MESSAGES, new JSONArray()
                        .put(new JSONObject()
                                .put(Emailv31.Message.TO, new JSONArray()
                                        .put(new JSONObject()
                                                .put("Email", "jahangir.shah@venturedive.com")
                                                .put("Name", "passenger 1")))
                                .put(Emailv31.Message.TEMPLATELANGUAGE, true)
                                .put(Emailv31.Message.TEMPLATEID, 602898)
                                .put(Emailv31.Message.SUBJECT, "Your email flight plan!")
                                .put(Emailv31.Message.VARIABLES, new JSONObject()
                                        .put("BOOKING", "Tuesday"))));
        response = client.post(request);

kindly explain this issue. as im providing every thing and it is working fine with post man

**Comment by adamyanliev** [comment]
Hello @jahangir1rashdi , apologies for the delayed response.

Looks like the `FROM` email address is missing from your payload. Without it the Send API cannot select the appropriate sender email, so the API returns a 400 status code. Keep in mind that the sender needs to be a validated one in your Mailjet account - you can find your registered senders [here](https://app.mailjet.com/account/sender).

Add this piece of code to your `message` object and enter your sender email address and name:

```
.put(Emailv31.Message.FROM, new JSONObject()
                        .put("Email", "pilot@mailjet.com")
                        .put("Name", "Mailjet Pilot"))
```

See the code sample here for more info: https://dev.mailjet.com/guides/?java#send-a-stored-template

Also keep in mind that in general this repository is dedicated to the documentation / API guides. In case you have questions or suggestions in that regard, feel free to submit an issue. In case you have issues with the functionality of the API itself, I'd suggest to post them in the [Java Wrapper Repo](https://github.com/mailjet/mailjet-apiv3-java).
