### ISSUE TITLE
Document how to get a contact's subscriptions

### ISSUE THREAD

**Issue by quinao** [mailjet/api-documentation#24]
Hello,

I use [mailjet's python client](https://github.com/mailjet/mailjet-apiv3-python) and I recently searched the email API documentation, in the "guides", for a way to retrieve a contact's subscriptions i.e. to know which contact lists a contact has subscribed to or unsubscribed from. I did not find it, which made me think the python client did not allow it.
However it is possible, by calling ``` mailjet_client.contact_getcontactslists.get(id=contact_id)```

I suggest to add this in the API guide, maybe under the "Manage contacts" section.

**Comment by adamyanliev** [comment]
Hi @quinao , 

thanks for the suggestion, we'll add the information to the guide.

Regards,
Atanas

**Comment by adamyanliev** [comment]
Hi again, 

we've updated the documentation today and added the info as you suggestion, so I'm closing this issue. Thanks again and feel free to suggest other improvements :)

Regards,
Atanas

**Comment by quinao** [comment]
Thank you!
