### ISSUE TITLE
"step":"confirmorder" instead of "step":"unavailable"

### ISSUE THREAD

**Issue by fermaf** [mailjet/api-documentation#5]
Hello, I find a mistake in your documentation.
(I sorry I'm newbie in github (and mailjet), that the reason I just let the image (right bottom corner))

![image](https://cloud.githubusercontent.com/assets/22239649/23336344/1193d392-fbac-11e6-9098-701e50e54104.png)

**Comment by fermaf** [comment]
the same in "refund" section code, is `"step":"refund"` instead of `"step":"unavailable"`

**Comment by Zhivko-Mailjet** [comment]
@fermaf 

Thank you for spotting the mistakes, we will address them in the next update of the documentation!

**Comment by Zhivko-Mailjet** [comment]
@fermaf 
I just wanted to let you know that the necessary changes have been made! Thanks again for your feedback!
