### ISSUE TITLE
Impossible de récupérer le messageID

### ISSUE THREAD

**Issue by MikaelHDX** [mailjet/api-documentation#7]
Bonjour,

Lorsque j'envoie un mail comme ceci par exemple : 
````
$body = [
'FromEmail' => "contact@MyDomain.com",
'FromName' => "MyDomain.com",
'Subject' => "Bienvenue sur MyDomain.com",
'MJ-TemplateID' => 149051,
'MJ-TemplateLanguage' => true,
'Recipients' => [
  [
    'Email' => $email,
    'Vars' => ['prenom' => $prenom]
  ]
]

];

$response = $mj->post(\Mailjet\Resources::$Email, ['body' => $body]);
````

Je récupère bien dans un array le messageID. Pour faire le test, je copie/colle l'int reçu.

Je fais ensuite comme dit dans votre doc :
````
$response = $mj->get(Resources::$Eventcallbackurl, ['id' => $id]);
$response->success() && var_dump($response->getData());
````

Je remplace $id par l'id copié/collé précédemment mais impossible d'avoir un retour de votre API sur le statut de mon mail.

Merci de votre aide.

**Comment by arnaudbreton** [comment]
Bonjour @MikaelHDX, merci pour votre message. Ce repository n'étant pas dédié à l'usage de l'API en PHP, je vous invite à contacter directement notre équipe support à [cette adresse](app.mailjet.com/support/ticket), en indiquant que votre requête concerne l'API. 

Notre équipe pourra alors vous proposer la meilleure solution à votre problème.

Merci d'avoir choisi Mailjet pour vos emails!
Cordialement.
