### ISSUE TITLE
Cannot use TemplateID in string format

### ISSUE THREAD

**Issue by eroneja** [mailjet/api-documentation#8]
Chapter 'Send API v3 to v3.1' mentions following about TemplateID

It used to accept string only, now it can accept 2 formats. When an integer is provided, we will search for the ID of the template. When a string is provided, we will search for the Name of the template.

I tried to use string format and it was not accepted (Integer format worked fine).

```json
"Messages": [
        {
            "Errors": [
                {
                    "ErrorIdentifier": "87f1eba9-a4da-4764-85f6-f2e8f346e43f",
                    "ErrorCode": "mj-0004",
                    "StatusCode": 400,
                    "ErrorMessage": "Type mismatch. Expected type \"integer\".",
                    "ErrorRelatedTo": [
                        "TemplateID"
                    ]
                }
            ],
            "Status": "error"
        }
]
```

**Comment by axi** [comment]
Found same thing today, please update doc or API

**Comment by ndiiorio** [comment]
Im with the same problem sending pdf attachments, could someone solve it?

**Comment by medmunds** [comment]
The same problem appears in the Mailjet template builder site: the curl example presented after editing a template shows the TemplateID parameter as a numeric string, but attempting to run the example as presented generates an mj-0004 error `ErrorMessage":"Type mismatch. Expected type \"integer\".","ErrorRelatedTo":["TemplateID"]`.

E.g., if your template id is 12345, publishing goes to https://app.mailjet.com/template/12345/send , where you're shown this curl example that incorrectly passes TemplateID as a string `"TemplateID": "12345"`:

```bash
# This call sends a message to the given recipient with vars and custom vars.
curl -s \
  -X POST \
  --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
  https://api.mailjet.com/v3.1/send \
  -H 'Content-Type: application/json' \
  -d '{
    "Messages":[
      {
        "From": {
          "Email": "validated-sender@your-domain.example.com",
          "Name": "Template Sender, Inc."
        },
        "To": [
          {
            "Email": "passenger1@mailjet.com",
            "Name": "passenger 1"
          }
        ],
        "TemplateID": "12345",
        "TemplateLanguage": true,
        "Subject": "Your order {{var:order}} was received",
        "Variables": {
    "order": "",
    "name": "MISSING NAME FIELD"
    }
      }
    ]
  }'
```

**Comment by adamyanliev** [comment]
Hello and apologies for the late reply. 

Using a string value for Template ID is possible for users who are on Send API v3 - on v3.1 it is only possible to enter an integer value. The template builder curl example field was fixed a while ago and now it displays the TemplateID as an integer value. The info in the guide will be updated shortly to clarify that string is only possible on Send API v3.

Thanks for letting us know - I'm closing this issue now.
