### ISSUE TITLE
Send API v3.1: Email without Name

### ISSUE THREAD

**Issue by medmunds** [mailjet/api-documentation#9]
[Couldn't find the source to [Send API v3.1](https://dev.mailjet.com/guides/#send-api-v3-1) in this repo to open a PR.]

All of the examples for [Send API v3.1](https://dev.mailjet.com/guides/#send-api-v3-1) show both an Email and a Name. It's not clear what to do if you have only the email address without a display-name.

From testing, it appears that all of the following work:

```json
  "To": [
    {"Email": "to1@example.com", "Name": ""},
    {"Email": "to2@example.com", "Name": null},
    {"Email": "to3@example.com"}
  ]
```

That is, you can pass Name as an empty string, a `null`, or omit the Name field entirely.

It would be good for the docs to clarify which approach is supported. (Applies to From, To, Cc, Bcc, and ReplyTo.)

**Comment by adamyanliev** [comment]
Hello,

Apologies for the delayed response.  You are correct - the `Name` property isn't mandatory and can be skipped entirely in the payload. We'll update the information in the next version of the guide.
